AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    Runtime: python3.9
    Timeout: 180
    Handler: main.lambda_handler
    Environment:
      Variables:
        TABLE_NAME: data-table
    Tags:
      ApplicationName: "UhohItsGonnaRainToday"
      Owner: "Ram"

Parameters:
  Api_Key_SecretManager_ARN:
    Type: String
    Default: arn:aws:secretsmanager:ap-southeast-2:698248325687:secret:OpenWeatherMapApiKey-lNcxq6

Resources:
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: UhOhItsGonnaRainMessages

  UhohItsGonnaRainTodayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UhohItsGonnaRainToday
      Environment:
        Variables:
          OMW_API_KEY_SECRETSMANAGER_ARN: !Ref Api_Key_SecretManager_ARN
          SNS_TOPIC_ARN: !GetAtt SnsTopic.TopicName
      PackageType: Zip
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SnsTopic.TopicName
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref Api_Key_SecretManager_ARN
