AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: python3.9
    Timeout: 180
    Handler: main.lambda_handler
    Environment:
      Variables:
        TABLE_NAME: data-table
    Tags: 
      ApplicationName: "UhohItsGonnaRainToday"
      Owner: "Ram"

Resources:
  SnsTopic:
    Type: AWS::SNS::Topic
    TopicName: UhOhItsGonnaRainMessages
    
  UhohItsGonnaRainTodayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UhohItsGonnaRainToday
      Environment:
        Variables:
          OMW_API_KEY: '{{resolve:secretsmanager:OpenWeatherMapApiKey:SecretString:ApiKey}}'
          SNS_TOPIC_ARN: !GetAtt SnsTopic.TopicName
      PackageType: Zip
      Policies:
      - SNSPublishMessagePolicy:
          TopicName:
            !GetAtt SnsTopic.TopicName